version: '2'
services:
        mongodb:
                container_name: "mongodb"
                image: mongo:latest
                environment:
                        - MONGO_DATA_DIR=/data/db
                        - MONGO_LOG_DIR=/dev/log
                volumes:
                        - ./data/db:/data/db
                ports:
                        - "27017:27017"
                command: mongod --smallfiles
        web:
                container_name: "amt-api"
                build: .
                restart: always
                links:
                        - mongodb:mongodb
                depends_on:
                        - mongodb
                ports:
                        - "3000:8080"

